version: '3'
services:
  db:
    container_name: wordpress_database
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress_db
    ports:
      - 3308:3306
  wordpress:
    container_name: wordpress_web
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8090:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_DATABASE=wordpress_db
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'phpmyadmin-wp'
        ports:
            - 8002:80
        restart: always
        links:
            - db
        depends_on:
            - db
volumes:
  persistent: